### PR TITLE
adding adx related features

### PR DESCRIPTION
**Pull request by miaoqi**
Hi Alex and Scott,

This is the version that support adx format. This version also make code values of each pixel to follow the order of "rgba". 

For testing purpose, you just need to "make" it and then go into "ctlrender" in the folder of "build". There is local executable called "ctlrender", so the command would be:

"./ctlrender  -ctl  pathToCTL  pathToDPX.dpx  pathTOADX.dpx  -format adx/adx10/adx16"

Let me know if it is correct, or I can work on it more.

Thanks,

Mio

### CODE REVIEW

**Comment by aforsythe** [comment]
Mio ... looks like all the files are showing as changed because of a file permissions issue.  Can you do `git config core.filemode false`, check out the master, recommit your changes, and resubmit the pull request?  Please check only the files that actually changed are showing as changed before doing the pull request.

**Comment by scottdyer** [comment]
I just got a chance to test this on Mac OSX 10.11 and ADX writing and reading seems to have worked. 

Note I did get the MACOSX_RPATH warning from cmake saying 
"MACOSX_RPATH is not specified for the following targets:

   IlmCtl
   IlmCtlMath
   IlmCtlSimd
   IlmImfCtl"

@miaoqi do you think we should we add compatibility for cmake 3+ behavior now by setting MACOSX_RPATH 1 in the cmakelist files? That seems to have worked for suppressing the error with the aces_container

**Comment by aforsythe** [comment]
@miaoqi consider resubmitting the pull request without the files in  ./testMaterials/  The binary is probably the biggest concern.

**Comment by miaoqi** [comment]
Hi,

I have updated the CMakeList. Also, I did not see "./testMaterials/" in either of the branches. Can you pull again?

Thanks,

Mio

**Comment by miaoqi** [comment]
Sorry, just saw "./testMaterials/" and updated the repository again. :)

**Comment by scottdyer** [comment]
@miaoqi do you know why do I get these warnings when writing an ADX?

    WARNING: adx 21.3 Reference Low Quality shall be Undefined
    WARNING: adx 21.5 Reference high quality shall be Undefined
    WARNING: adx 21.7 Transfer characteristic shall be ADX
    WARNING: adx 21.8 Colorimetric characteristic shall be ADX

The file seems to be written fine, but I'm wondering why the warnings?

**Comment by scottdyer** [comment]
Also, do you know what we need to add or change in CMakeLists to avoid the following error?

````
CMake Warning (dev) at CMakeLists.txt:88 (install):
  Policy CMP0062 is not set: Disallow install() of export() result.  Run
  "cmake --help-policy CMP0062" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The file

    /Users/scott/Documents/work/aces/src/CTL/build/CTLLibraryDepends.cmake

  was generated by the export() command.  It should not be installed with the
  install() command.  Use the install(EXPORT) mechanism instead.  See the
  cmake-packages(7) manual for more.
````
Cmake says this about the policy.

````
CMP0062
-------

Disallow install() of export() result.

The ``export()`` command generates a file containing
:ref:`Imported Targets`, which is suitable for use from the build
directory.  It is not suitable for installation because it contains absolute
paths to buildsystem locations, and is particular to a single build
configuration.

The ``install(EXPORT)`` generates and installs files which contain
:ref:`Imported Targets`.  These files are generated with relative paths
(unless the user specifies absolute paths), and are designed for
multi-configuration use.  See :ref:`Creating Packages` for more.

CMake 3.3 no longer allows the use of the ``install(FILES)`` command
with the result of the ``export()`` command.

The ``OLD`` behavior for this policy is to allow installing the result of
an ``export()`` command.  The ``NEW`` behavior for this policy is
not to allow installing the result of an ``export()`` command.

This policy was introduced in CMake version 3.3.  CMake version
3.3.2 warns when the policy is not set and uses ``OLD`` behavior.  Use
the ``cmake_policy()`` command to set it to ``OLD`` or ``NEW``
explicitly.

.. note::
  The ``OLD`` behavior of a policy is
  ``deprecated by definition``
  and may be removed in a future version of CMake.
````

**Comment by miaoqi** [comment]
Hi,

CTLRENDER will read the meta data first on each of these fields. If any of them do not match the specifications of adx format, CTLRENDER will force it be the values defined by the standards.

The warnings are printed out for the purpose of reminding users what have been changed when writing out adx file.

Thanks,

Mio


[Δ]<http://www.oscars.org>


Miaoqi Zhu
Lab Systems Administrator


Academy of Motion Picture Arts and Sciences
Science & Technology Council
1313 Vine Street • Hollywood, CA 90028


310.247.3000 x3302 • MZhu@oscars.org<mailto:MZhu@oscars.org>

**Comment by miaoqi** [comment]
Hi,

I will look it shortly.

Thanks,

Mio


[Δ]<http://www.oscars.org>


Miaoqi Zhu
Lab Systems Administrator


Academy of Motion Picture Arts and Sciences
Science & Technology Council
1313 Vine Street • Hollywood, CA 90028


310.247.3000 x3302 • MZhu@oscars.org<mailto:MZhu@oscars.org>

**Comment by miaoqi** [comment]
Hi all,

I think i have mitigated the warning from install (export). You can check if the fix has solved the issue on yours.

https://cmake.org/Wiki/CMake/Tutorials/Exporting_and_Importing_Targets

Thanks,

Miaoqi

**Comment by miaoqi** [comment]
Hi,

Just a quick question, are we supporting adx with the depth bit of 1, 8 in addition to 10 and 16? 

From the specifications, there seems to be 1, 8, 10 and 16 bit.

Thanks,

Mio

**Comment by aforsythe** [comment]
The spec specifies those bit depths for image element 2 which is intended for dust maps, not the primary image data.
If we don’t currently support image element 2 in the implementation we should note that.


On October 26, 2015 at 3:28:51 PM, Mio Zhu (notifications@github.com) wrote:
> Hi,
>
> Just a quick question, are we supporting adx with the depth bit of 1, 8 in addition to 10
> and 16?
>
> From the specifications, there seems to be 1, 8, 10 and 16 bit.
>
> Thanks,
>
> Mio
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/ampas/CTL/pull/60#issuecomment-151302878

[?]<http://www.oscars.org>


Alex Forsythe
Image Engineering Manager


Academy of Motion Picture Arts and Sciences
Science & Technology Council
1313 Vine Street • Hollywood, CA 90028


323.817.4170 • aforsythe@oscars.org<mailto:aforsythe@oscars.org>

**Comment by miaoqi** [comment]
Thanks for the quick reply!

I think it supports element#2 only if it reads information of the second element from reading the dpx file. I have code that does that.

**Comment by miaoqi** [comment]
If the input dpx is not of 10 bit or 16 bit by reading the information from the first element, the program will print out an error message and quit. If the second element is written, the program will support 1, 8 or 16 just for the second element.

**Comment by miaoqi** [comment]
Please note if you use "iinfo -v" to examine the meta data of a converted adx image. It probably shows:

dpx:Transfer: "Undefined"
dpx:Colorimetric: "Undefined"

However, the specifications say it should be "adx". The guess is that "openimageio" probably has not incorporated "adx" format yet, that is why it is "undefined". 

Thanks,

Mio

**Comment by scottdyer** [comment]
Mio, Please open a new pull request from your current adx branch.

**Comment by scottdyer** [comment]
Nevermind. Looks like I can do it.

**Comment by miaoqi** [comment]
Sorry, I was working on the PC laptop thus was not close the email. Apologize for it!

**Pull request closed without merging**
