### PR TITLE
Update build system

### PR DESCRIPTION
**Pull request by waebbl**
The patches pick up some ideas from issue #100 

- Consequently use the variables provided by GNUInstallDirs
- Simplify finding OpenEXR and IlmBase / Imath. OpenEXR looks for either IlmBase (<OpenEXR-3) or Imath (>=OpenEXR-3), so we don't find these dependencies explicitly and only search for OpenEXR with a version provided
- Testing is enabled globally (enable_testing), but we have a `CMAKE_BUILD_TESTS` variable. Guard the call of this function by the cmake option.

Bug: https://github.com/ampas/CTL/issues/100
Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>

### CODE REVIEW

**Comment by michaeldsmith** [comment]
@waebbl thanks for the contribution, this looks really good and I like the simpler process.  The only issue is it looks like the CI is failing to build under MacOs 

image

The valgrind and Windows-vcpkg-test CIs are failing due to issue #109 that I'm working on

**Comment by michaeldsmith** [comment]
It looks like the compiler can't `find `half when building with OpenEXR 2 under MacOs

image

**Comment by waebbl** [comment]
Is it possible that it's not recognizing the `noexcept` keyword? Would it help to pass a certain C++ standard to use?

**Review by michaeldsmith — APPROVED** [review]

**Comment by michaeldsmith** [comment]
@waebbl your suggestion worked, requiring C++ 11 fixed the MacOs OpenEXR 2 build issue.

**Comment by michaeldsmith** [comment]
@waebbl do you think this PR also addresses the GNUInstallDirs issue mentioned in PR https://github.com/ampas/CTL/pull/67 ?

**Comment by waebbl** [comment]
> @waebbl do you think this PR also addresses the GNUInstallDirs issue mentioned in PR #67 ?

Yes it should, at least mostly. Some of that PR is outdated, some is fixed with my PR in conjunction with your changes to use GNUInstallDirs.
What my PR doesn't address yet, is the configuration and installation of pkg-config and cmake config files, which is currently not done by the build system. PR #67 includes some patches for the pkg-config files as well, but I'm not sure if the changes are still up-to-date.
That patch was from another Gentoo fellow dev and we used it for a long time, but with the latest patch, supporting OpenEXR-3 / Imath, I no longer need that patch.

**Comment by michaeldsmith** [comment]
one more build system question @waebbl, do you think we still need the files in `\CTL\config` directory and the following lines in `\OpenEXR_CTL\CMakeLists.txt` ? 

```
if ( PKG_CONFIG_FOUND )
    configure_file(../config/OpenEXR_CTL.pc.in "${PROJECT_BINARY_DIR}/OpenEXR_CTL.pc" @ONLY)
    install( FILES "${PROJECT_BINARY_DIR}/OpenEXR_CTL.pc" DESTINATION lib/pkgconfig COMPONENT dev )
endif()
```

**Comment by waebbl** [comment]
It depends.
Many packages which provide _new_ cmake config files, still provide their _old_ pkg-config files as well. So it's up to you, if you still want to distribute the pkg-config files together with cmake config files, we should keep the portion from the CMakeLists.txt file you quoted. But those lines should be prepended by a find_package call for pkg-config.

For the files in `CTL/config`. If you want to install the pkg-config files, you als need the `*.pc.in` files. The `*.cmake.in` files, however, are not needed IMO, as the cmake config files should preferably be created using cmake functions from `CMakeConfigPackageHelpers`.

**Comment by waebbl** [comment]
How could I preserve your additions and still edit the files I've changed, i.e. to clean up. Can I just `pull` your changes into my local branch?

**Comment by michaeldsmith** [comment]
@waebbl I pushed my additions to your forked repo [waebbl/CTL](https://github.com/waebbl/CTL) update-build branch https://github.com/waebbl/CTL/tree/update-build  so I think you can just do git pull on your update-build branch https://github.com/waebbl/CTL/tree/update-build

**Comment by michaeldsmith** [comment]
@waebbl do you use the pkg-config files in your gentoo package?  If not, I'd rather simplify and remove the pkg-config stuff.

**Comment by waebbl** [comment]
> @waebbl I pushed my additions to your forked repo [waebbl/CTL](https://github.com/waebbl/CTL) update-build branch https://github.com/waebbl/CTL/tree/update-build so I think you can just do git pull on your update-build branch https://github.com/waebbl/CTL/tree/update-build

Thanks, I could just update it in the browser interface.



> @waebbl do you use the pkg-config files in your gentoo package? If not, I'd rather simplify and remove the pkg-config stuff.

We currently don't have consumers of the ctl package, so we don't need the pkg-config files. I'm ok with dropping those.

**Comment by michaeldsmith** [comment]
@waebbl i pushed a commit to your `update-build` branch that removes the `\CTL\config` directory and removes the following code from `\OpenEXR_CTL\CMakeLists.txt` 

```
if ( PKG_CONFIG_FOUND )
    configure_file(../config/OpenEXR_CTL.pc.in "${PROJECT_BINARY_DIR}/OpenEXR_CTL.pc" @ONLY)
    install( FILES "${PROJECT_BINARY_DIR}/OpenEXR_CTL.pc" DESTINATION lib/pkgconfig COMPONENT dev )
endif()

```
If you don't see any issues with this, let me know and I'll merge the PR

**Comment by waebbl** [comment]
@michaeldsmith I cleaned up the code somewhat and actually removed the previously only commented lines of code.
In don't see any issues removing the directory and the pkg-config related code from the CMakeLists.txt file.

**Comment by waebbl** [comment]
Thanks!

**Pull request merged**
