### PR TITLE
Issues/0111 ctlrender pickup module_name function (#111)

### LINKED ISSUE #111: Not having a main() function causes a crash on Windows
According to the CTL spec. all CTL files must contain either a `main()` function or a function with the same name as the source file. However in Windows only the `main()` function approach works as the way this is implemented in `ctlrender` is whatever is after the last `/` in the file path of the ctl file is looked for as a function name. This breaks on Windows as Windows uses `\` rather than `/`. This is even mentioned in a comment in `transform.cc`.

My proposed solution is to use `#ifdef WIN32` to look for backslashes rather than forward slashes in `transform.cc:346`. I'll also have a look at adding a test for this but I'm not sure how far I'll get with that as I've never used this test suite before.

### PR DESCRIPTION
**Pull request by ThomasWilshaw**
* fix module main function finding on Windows

* add improved error handling when correct function name cannot be found

Fixes #111

### CODE REVIEW

**Comment by michaeldsmith** [comment]
Can you try adding a test for this so it could be run with Ctest ?

I think you just need to add something like this to \CTL\unittest\ctlrender\CMakeLists.txt

`add_test(NAME "ctlrender-ctl-function-name-is-filename" COMMAND ctlrender -force -ctl functionname_is_filename.ctl bars_photoshop.exr out.exr)`

and then add the CTL file `functionname_is_filename.ctl` to the folder \CTL\unittest\ctlrender\

**Comment by michaeldsmith** [comment]
@ThomasWilshaw you could also try allowing changes on your pull request so I could try to collaborate with you on the code and tests.  I think you would need to follow these instructions https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by ThomasWilshaw** [comment]
Allow Edits by Maintainers is already checked on the PR so you should be good to do any edits you need.

Thanks, I wasn't sure how best to add this test so I'll give that a try.

**Comment by michaeldsmith** [comment]
@ThomasWilshaw I just tried running Ctest with your func_name branch, I think the current ctlrender tests may actually already be testing the function-name-is-filename feature that you fixed for windows, since test.sh uses the `-ctl unity.ctl` argument and `unity.ctl` contains the following:

```
void unity
    (output varying half rOut,
     output varying half gOut,
     output varying half bOut,
     input varying half rIn,
     input varying half gIn,
     input varying half bIn)
{
  rOut=rIn;
  gOut=gIn;
  bOut=bIn;
}
```

**Comment by michaeldsmith** [comment]
It seems your fix works for when calling ctlrender from windows command prompt and windows powershell, like this

`ctlrender.exe -force -ctl ..\unittest\ctlrender\functionname_is_filename.ctl ..\unittest\ctlrender\bars_photoshop.exr out.exr`

And this makes sense since both windows command prompt and windows powershell use normal windows paths like C:\temp with a backslash character \

But it doesn't seem to work with git bash in windows or wsl that use paths with forward slash character / like this:

```
Mike@blade13-2020 MINGW64 /c/temp/ThomasWilshawCTL/CTL/build (func_name)
$ ./ctlrender/Debug/ctlrender.exe -force -ctl ../unittest/ctlrender/functionname_is_filename.ctl ../unittest/ctlrender/bars_photoshop.exr out.exr
exception thrown (oops...): CTL file must contain either a main or <module_name> (../unittest/ctlrender/functionname_is_filename) function
```

**Comment by michaeldsmith** [comment]
Does it make sense to check for both \ and / and use which ever is found ?

**Comment by ThomasWilshaw** [comment]
That seems reasonable, I can't imagine a path having both forward and back slashes. Is it worth adding a test that deliberately fails as well? I.e. to make sure we properly handle an inccorect function name?

**Comment by michaeldsmith** [comment]
If it were possible, this would pick the largest value (closest to the end of the string).

```
char *backslash = strrchr(name, '\\');
char *forwardslash = strrchr(name, '/');
slash = backslash > forwardslash ? backslash : forwardslash;
```

**Comment by michaeldsmith** [comment]
yeah, i think we should test a CTL file that doesn't include either the filename-as-functionname or main() and it should fail.  I've never used `add_test()` for a test that should fail.

**Comment by michaeldsmith** [comment]
The `add_test() `documentation says the `WILL_FAIL` property should be set for a test that should fail 

https://cmake.org/cmake/help/latest/command/add_test.html

**Review by michaeldsmith — APPROVED** [review]
looks good - thanks for the contribution!

**Pull request merged**
